import trimesh

from app.schemas.machining import MachiningParams
from app.services.conversion_service import convert_mesh


def test_conversion_service_returns_real_gcode_for_simple_box():
    mesh = trimesh.creation.box(extents=(10, 10, 4))
    result = convert_mesh(mesh, "box.stl", MachiningParams(step_down_mm=1.0, strategy="contour"))

    assert result["status"] == "success"
    assert result["linesCount"] > 10
    assert result["report"]["conversionSuccess"] is True
    assert result["report"]["layersCount"] > 0
    assert "; Program generated by G-Coder" in result["gcode"]
    assert "M30" in result["gcode"]
